#!/usr/bin/env python
# -*- coding: utf-8 -*-


__author__ = {'name' : 'Wei Qiao',
	      'mail' : 'qiaowei@tamu.edu'}


class HuffmanCoding:
	p_dic = {}   #a dictionary to store the number of occurence of each symbol
	summ = 0.0
	coding_sequence = ""
	coded_sequence = ""
        decoded_sequence = ""
	coding_dic = {}
        decoding_dic = {}
        symbols_table = []
        p_table = []

	def __init__(self):
		x=1

	def coder(self,coding_sequence):
		self.coding_sequence = coding_sequence
		self.caculateP(self.coding_sequence)
	        for (key,val) in self.p_dic.items():#sort keys according to their occurence frequencies
                        self.arrange(key,val)
                self.genCodingtable()
                for s in self.coding_sequence:
                        self.coded_sequence = self.coded_sequence+self.coding_dic[s]
        def getCodedsequence(self):
                return self.coded_sequence
       
        def genCodingtable(self):
                self.coding_dic[self.symbols_table[0]] = "0"
                for i in range(1,len(self.symbols_table)):
                       self.coding_dic[self.symbols_table[i]] = self.coding_dic[self.symbols_table[i-1]]+"1"
                         
        def arrange(self,key,val):
                for i in range(len(self.p_table)):
                        if(val>self.p_table[i]):
                                self.p_table.insert(i,val)
                                self.symbols_table.insert(i,key)
                                return
                self.p_table.append(val)
                self.symbols_table.append(key)

        def genDecodingDic(self):
                for (key,val) in self.coding_dic.items():
                        self.decoding_dic[val] = key

        def caculateP(self,coding_sequence):
		for s in coding_sequence:
			self.summ = self.summ+1
			if self.p_dic.get(s): self.p_dic[s]=self.p_dic[s]+1.0
			else: self.p_dic[s] = 1.0
		for key in self.p_dic:  
			self.p_dic[key] = self.p_dic[key]/self.summ

	def decoder(self):
	        #worked using the generated codes and the probabilities
                self.genDecodingDic()
                if len(self.coded_sequence) <1: return
                s = self.coded_sequence[0]
                for i in range(1,len(self.coded_sequence)):
                        if self.coded_sequence[i] != "0":
                                s = s+self.coded_sequence[i]
                        else:
                                self.decoded_sequence = self.decoded_sequence+self.decoding_dic[s]
                                s = self.coded_sequence[i]
                self.decoded_sequence = self.decoded_sequence+self.decoding_dic[s]
        def getDecodedsequence(self):
                return self.decoded_sequence	


if __name__=="__main__":
	codec = HuffmanCoding()
	s=raw_input("Please input the symbols you want to code uisng Huffman:\n")
	codec.coder(s)  
        print "The coding dictionary generated by Huffman coding is:"
        for (key,val) in  codec.coding_dic.items():
                print key,val
        print "The coded sequence is:"
        print codec.getCodedsequence()
        codec.decoder()
        print "The decoded sequence is:"
        print codec.getDecodedsequence()
		
